version: "3.9"
services:
  chatgptslackbot:
    build:
      context: .
    image: chatgptslackbot
    restart: always
    container_name: chatgptslackbot
    env_file:
      - .env
    ports:
      - "8000:8000"
